### ISSUE TITLE
References

### ISSUE THREAD

**Issue by Sciroccogti** [seu-labview/RGB-D-modeling#1]
* [RGB-D 3D建模算法参考](https://github.com/ClaireXie/modeling_3d)
* [开源激光3D扫描方案](https://fabscan.org/)，[外壳github](https://github.com/mariolukas/FabScan-Case)
* [多视角点云三维重构](http://www.sohu.com/a/338907351_100007727)，[对应代码](https://github.com/callmeray/PointMVSNet "github")
* [开源RGB+激光扫描仪](https://github.com/LibreScanner/ciclop)
* [三维重建 3D reconstruction 有哪些实用算法？](https://www.zhihu.com/question/29885222/answer/918009389)

**Comment by Sciroccogti** [comment]
3D建模的过程实际上是一个三维重建过程，这个过程包括点云数据预处理、分割、三角网格化、网格渲染。

由于激光扫描获取的数据中常常伴有杂点或噪声，影响了后续的处理，因此为了获取完整的模型，需要对点云数据进行一定的预处理，常用的方法有滤波去噪、数据精简、数据插补等。

分割是指将整个点云聚类为多个点云，每个点云对应独立的物体对象。分割算法大体上是先选定一个点，利用kd树计算以该点为中心的球，球内的点都属于该物体，球的半径设为一个阈值，之后遍历该物体的其他点都这么处理，最终会将点云分割成一个一个的物体。

为了便于后续的网格渲染，需要提前将点云进行三角网格化，采用的算法通常是凸包或凹包算法。

以上几步基本上已经得出了点云的空间拓扑结构，要得到逼真的物体，还需要网格渲染。网格渲染主要为纹理映射，就是将数码相机中的图像望网格上贴。

经过以上几步就完成了整个3D建模。
————————————————
版权声明：本文为CSDN博主「lming_08」的原创文章，遵循 CC 4.0 BY-SA 版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/lming_08/article/details/18411931

**Comment by molguitianzn** [comment]
https://www.bilibili.com/video/av54766670?from=search&seid=5543960533686970393

autoCad教程

**Comment by Sciroccogti** [comment]
⚠️ !!DO NOT GET TOO CLOSE TO THE LASER!!

## How to install astra SDK on ubuntu 20.04

### Prebuilt (Recommended)

1. Download SDK [here](https://orbbec3d.com/develop/)
2. `sudo sh ./install/install.sh`:
  > The NOTES after the installation is wrong! You should use `path/to/AstraSDK/include` and `path/to/AstraSDK/lib` instead of `path/to/AstraSDK/install/xxx`
3. `cd samples && cmake . && make`
4. `cd bin` and use `sudo` to run some samples

REMEMBER: you must plug the camera [in the primary USB port](https://github.com/orbbec/astra/issues/3).

### Self build (Not recommended)

Add `#include <stdio.h>` in `src/astra_core/astra_plugin_service.hpp`

```Bash
sudo apt install libsfml-dev libopenni2-dev clisp

git clone --recursive https://github.com/orbbec/astra
cd astra
mkdir build
cmake ..
```

**Comment by Sciroccogti** [comment]
[astra SDK](https://developer.orbbec.com.cn/technical_library/astra_sdk/md__d_1__xE5_xB7_xA5_xE4_xBD_x9C__a_io_t_xE4_xBA_x8B_xE4_xB8_x9A_xE9_x83_xA8__s_d_k_2_81__xE6_x9f750aa7ec321b8bd550e5986a50986ea.html)

**Comment by Sciroccogti** [comment]
## Mask RCNN

We are using nvidia docker. See the tutorial here: [install-guide](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#installing-on-ubuntu-and-debian)

### Install
Below is modified from [the official tutorial](https://ngc.nvidia.com/catalog/resources/nvidia:mask_r_cnn_for_tensorflow2/quickStartGuide).
```Bash
git clone https://github.com/NVIDIA/DeepLearningExamples.git
cd DeepLearningExamples/TensorFlow2/Segmentation/MaskRCNN
sudo bash ./scripts/docker/build_tf2.sh
```
